### ISSUE TITLE
When will the code be open sourced?

### ISSUE THREAD

**Issue by Herython** [somuchtome/SimAC#1]

**Comment by somuchtome** [comment]
Sorry for the late, the code will be released before the meeting.

**Comment by cirteo** [comment]
The meeting should be held today. Will the code open sourced today?

**Comment by somuchtome** [comment]
Thank you for your reminder, we have released the code. If you have any questions, don't hesitate to contact me.

**Comment by Herython** [comment]
Thanks! 😊
